### ISSUE TITLE
Fine Tune Flexbox setup

### ISSUE THREAD

**Issue by keefe** [keefe/categorizeus#41]
Resources: 

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Using_CSS_flexible_boxes

https://developer.mozilla.org/en-US/docs/Web/CSS/align-items

http://codepen.io/justd/pen/yydezN

http://the-echoplex.net/flexyboxes/

https://css-tricks.com/snippets/css/a-guide-to-flexbox/

https://scotch.io/tutorials/a-visual-guide-to-css3-flexbox-properties

https://kartikprabhu.com/articles/equal-height-images-flexbox

https://www.taniarascia.com/how-to-build-a-responsive-image-gallery-with-flexbox/

https://codepen.io/dudleystorey/pen/Kgofa?js-preprocessor=none

https://www.sitepoint.com/using-modern-css-to-build-a-responsive-image-grid/

http://codepen.io/SitePoint/pen/bEvVqP

https://michaelward82.wordpress.com/2015/11/24/how-to-make-a-super-simple-responsive-image-gallery-layout-with-flexbox/

https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis

https://css-tricks.com/filling-space-last-row-flexbox/

http://flexboxfroggy.com/

**Comment by kroeders** [comment]
I guess what I meant here was to fine tune both the grid itself and the overall page layout, considering adding some kind of a right side informational panel similar to github, twitter, etc.
